[package]
name = "ort"
version = "0.3.0"
edition = "2024"
description = "Open Router CLI"
authors = ["Graham King <graham@gkgk.org>"]
license = "MIT"
repository = "https://github.com/grahamking/ort"

[[bin]]
name = "ort"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
strip = true
codegen-units = 1
panic = "abort"
lto = true

[dependencies]

