cargo-features = ["panic-immediate-abort"]

[workspace]
members = ["core", "cli"]
default-members = ["core"]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"
description = "Open Router CLI"
authors = ["Graham King <graham@gkgk.org>"]
license = "MIT"
repository = "https://github.com/grahamking/ort"

[profile.dev]
panic = "immediate-abort"

[profile.release]
opt-level = "s"
strip = true
codegen-units = 1
panic = "immediate-abort"
lto = true
