cargo-features = ["panic-immediate-abort", "profile-rustflags"]

[workspace]
members = ["core", "cli"]
resolver = "3"

[workspace.package]
version = "0.3.2"
edition = "2024"
description = "Open Router CLI"
authors = ["Graham King <graham@gkgk.org>"]
license = "MIT"
repository = "https://github.com/grahamking/ort"
readme = "README.md"

[workspace.dependencies]
ort-openrouter-core = { path = "core", version = "0.3.2" }

[profile.release]
opt-level = "s"
strip = true
codegen-units = 1
panic = "immediate-abort"
lto = true
rustflags = ["-Ctarget-cpu=native", "-Crelocation-model=static", "-Clink-args=-Wl,--build-id=none,--no-eh-frame-hdr", "-Cforce-frame-pointers=yes"]
