[workspace]
members = ["cli", "core"]
resolver = "3"

[workspace.package]
version = "0.2.1"
edition = "2024"
description = "Open Router CLI"
authors = ["Graham King <graham@gkgk.org>"]
license = "MIT"
repository = "https://github.com/grahamking/ort"

[profile.release]
opt-level = "s"
strip = true
codegen-units = 1
panic = "abort"
lto = true
