[toolchain]
channel = "nightly-2026-01-07"
components = ["rust-src", "rust-analyzer"]

# Ideal for `cargo install`
#profile = "minimal"
# Better for local dev
#profile = "default"
# ..so what should we do?
